export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_TWITS_DATA = "SET_TWITS_DATA";
export const ADD_TWITS_SYMBOL = "ADD_TWITS_SYMBOL";
export const UPDATE_TWITS_SYMBOL_INPUT = "UPDATE_TWITS_SYMBOL_INPUT";
export const GET_TWITS_USER_SYMBOLS = "GET_TWITS_USER_SYMBOLS";
export const UPDATE_TWITS_SYMBOL_NOT_FOUND = "UPDATE_TWITS_SYMBOL_NOT_FOUND";